### ISSUE TITLE
Acceptance test error: node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by eshtadc** [dollarshaveclub/ember-shave#3]
When I use ember-shave in an acceptance test I get the following error upon teardown of the test:

`Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.     at clear (https://dev.apple.com:4200/assets/vendor.js:27797:20)     at SafeStringUpsert.update (https://dev.apple.com:4200/assets/vendor.js:28408:39)     at OptimizedCautiousUpdateOpcode.evaluate (https://dev.apple.com:4200/assets/vendor.js:28588:34)     at UpdatingVM.execute (https://dev.apple.com:4200/assets/vendor.js:32411:24)     at RenderResult.rerender (https://dev.apple.com:4200/assets/vendor.js:32769:16)     at RootState._this.render (https://dev.apple.com:4200/assets/vendor.js:44814:25)     at exports.runInTransaction (https://dev.apple.com:4200/assets/vendor.js:48305:29)     at InteractiveRenderer._renderRoots (https://dev.apple.com:4200/assets/vendor.js:45086:81)     at InteractiveRenderer._renderRootsTransaction (https://dev.apple.com:4200/assets/vendor.js:45124:14)     at InteractiveRenderer._revalidate (https://dev.apple.com:4200/assets/vendor.js:45163:12)
--`

I think this is due to have shave removes elements from the DOM and re-creates them. Have you seen anything like this before?

**Comment by yowainwright** [comment]
@eshtadc I'll looking into this soon. Sorry it took so long for me to see this. 🙏
